using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using DevExpress.XtraTreeList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace DXWinForm
{
    public partial class Main_Form : XtraForm
    {
        private readonly string connectionString;

        public Main_Form()
        {
            InitializeComponent();
            connectionString = ConfigurationManager.ConnectionStrings["DataBase_Noke_system"].ConnectionString;
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void Main_Form_Load(object sender, EventArgs e)
        {
            // 直接调用管理器的方法
            PermissionManager pm = new PermissionManager(this, connectionString);
            pm.SyncModulesToDatabase();
            HideAllPage.HideAllPages(xtraTabControl1);
            pm.ApplyPermissions();
        }


        private void barButtonItem1_ItemClick(object sender, ItemClickEventArgs e)
        {
            用户管理.PageVisible = true;
            xtraTabControl1.SelectedTabPage = 用户管理;
        }

        private void barButtonItem2_ItemClick(object sender, ItemClickEventArgs e)
        {
            角色管理.PageVisible = true;
            xtraTabControl1.SelectedTabPage = 角色管理;

            // 1. 加载权限树
            LoadPermissionsTree(treeList1);

            // 2. 加载角色列表
            LoadRolesToListBox();

            // 3. 如果有选中角色，勾选其权限
            if (listBoxControl1.Items.Count > 0)
            {
                listBoxControl1.SelectedIndex = 0; // 默认选中第一个角色
            }
        }
        public void LoadPermissionsTree(TreeList treeList)
        {
            treeList.BeginUpdate();
            treeList.ClearNodes();
            treeList.OptionsView.ShowCheckBoxes = true;
            // 1. 从数据库读取所有权限
            DataTable dt = new DataTable();
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string sql = "SELECT PermissionCode, ParentCode, Description FROM Permissions";
                SqlDataAdapter da = new SqlDataAdapter(sql, conn);
                da.Fill(dt);
            }

            // 2. 绑定数据源
            treeList.DataSource = dt;

            // 3. 设置层级字段
            treeList.KeyFieldName = "PermissionCode";
            treeList.ParentFieldName = "ParentCode";

            treeList.ExpandAll();
            treeList.EndUpdate();
        }

        private void LoadRolesToListBox()
        {
            listBoxControl1.Items.Clear();

            // 假设您的数据库有名为 Roles 的表
            string sql = "SELECT RoleID, RoleName FROM Roles";

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand(sql, conn);
                conn.Open();
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        // 将 RoleID 存储在 Tag 中，RoleName 显示出来
                        var item = new DevExpress.XtraEditors.Controls.ImageListBoxItem();
                        item.Value = reader["RoleName"].ToString();
                        item.Tag = reader["RoleID"]; // 绑定ID用于后续查询
                        listBoxControl1.Items.Add(item);
                    }
                }
            }
        }
        private void LoadRolePermissionsIntoTree(TreeList treeList, int roleId)
        {
            // 获取角色权限
            List<string> rolePermissionCodes = new List<string>();
            string sql = "SELECT PermissionCode FROM RolePermissions WHERE RoleID = @RoleID";
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@RoleID", roleId);
                conn.Open();
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        rolePermissionCodes.Add(reader["PermissionCode"].ToString());
                    }
                }
            }

            // 遍历节点并勾选
            treeList.BeginUpdate();
            treeList.UncheckAll();
            foreach (DevExpress.XtraTreeList.Nodes.TreeListNode node in treeList.Nodes)
            {
                CheckNodeRecursive(node, rolePermissionCodes);
            }
            treeList.EndUpdate();
        }

        // 新增的递归辅助方法
        private void CheckNodeRecursive(DevExpress.XtraTreeList.Nodes.TreeListNode node, List<string> rolePermissionCodes)
        {
            string code = node["PermissionCode"]?.ToString();
            if (!string.IsNullOrEmpty(code) && rolePermissionCodes.Contains(code))
            {
                node.Checked = true;
            }

            // 递归检查子节点
            foreach (DevExpress.XtraTreeList.Nodes.TreeListNode childNode in node.Nodes)
            {
                CheckNodeRecursive(childNode, rolePermissionCodes);
            }
        }
        private void listBoxControl1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listBoxControl1.SelectedItem is DevExpress.XtraEditors.Controls.ImageListBoxItem item)
            {
                int roleId = Convert.ToInt32(item.Tag);
                // 仅在 TreeList 已经有节点时才调用
                if (treeList1.Nodes.Count > 0)
                    LoadRolePermissionsIntoTree(treeList1, roleId);
            }
        }

        private void btnSavePermissions_Click(object sender, EventArgs e)
        {
            if (listBoxControl1.SelectedItem is DevExpress.XtraEditors.Controls.ImageListBoxItem item)
            {
                int roleId = Convert.ToInt32(item.Tag);

                // 获取选中的权限
                List<string> selectedPermissions = new List<string>();
                foreach (DevExpress.XtraTreeList.Nodes.TreeListNode node in treeList1.Nodes)
                {
                    CollectCheckedPermissions(node, selectedPermissions);
                }

                // 保存到数据库
                SaveRolePermissions(roleId, selectedPermissions);

                XtraMessageBox.Show("权限保存成功！", "提示");
            }
        }
        private void CollectCheckedPermissions(DevExpress.XtraTreeList.Nodes.TreeListNode node, List<string> list)
        {
            string code = node["PermissionCode"]?.ToString();
            if (!string.IsNullOrEmpty(code) && node.Checked)
            {
                list.Add(code);
            }

            foreach (DevExpress.XtraTreeList.Nodes.TreeListNode child in node.Nodes)
            {
                CollectCheckedPermissions(child, list);
            }
        }
        private void SaveRolePermissions(int roleId, List<string> permissionCodes)
        {
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();

                // 1. 删除已有权限
                using (SqlCommand delCmd = new SqlCommand("DELETE FROM RolePermissions WHERE RoleID = @RoleID", conn))
                {
                    delCmd.Parameters.AddWithValue("@RoleID", roleId);
                    delCmd.ExecuteNonQuery();
                }

                // 2. 插入新权限
                string insertSql = "INSERT INTO RolePermissions(RoleID, PermissionCode) VALUES(@RoleID, @PermissionCode)";
                using (SqlCommand insCmd = new SqlCommand(insertSql, conn))
                {
                    insCmd.Parameters.Add("@RoleID", System.Data.SqlDbType.Int);
                    insCmd.Parameters.Add("@PermissionCode", System.Data.SqlDbType.VarChar, 50);

                    foreach (var code in permissionCodes)
                    {
                        insCmd.Parameters["@RoleID"].Value = roleId;
                        insCmd.Parameters["@PermissionCode"].Value = code;
                        insCmd.ExecuteNonQuery();
                    }
                }
            }
        }
    }
}